---
- name: Import facts
  ansible.builtin.include_role:
    name: "{{ item }}"
    tasks_from: facts
  loop:
    - k3s
    - certmanager
    - basic_auth

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml

- name: Role Provisioning
  when: ansible_host in k3s_server_hosts
  block:
    - name: Validate service state
      ansible.builtin.wait_for:
        port: "{{ k3s_vars.server.api.port }}"
        state: started
        timeout: 30
      any_errors_fatal: true

    - name: Add repository
      kubernetes.core.helm_repository:
        name: "{{ rook_ceph_vars.kubernetes.helm.repository.name }}"
        repo_url: "{{ rook_ceph_vars.kubernetes.helm.repository.url }}"

    - name: Chart Setup
      run_once: true
      block:
        - name: Install rook-ceph operator
          kubernetes.core.helm:
            chart_ref: "{{ rook_ceph_operator_project_chart }}"
            chart_version: "{{ rook_ceph_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ rook_ceph_vars.kubernetes.helm.chart.operator.name }}"
            namespace: "{{ rook_ceph_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'operator_values.j2') | from_yaml }}"
            wait: true
          register: result
          delay: 1
          retries: 3
          until: result is not failed

        - name: Install rook-ceph cluster
          kubernetes.core.helm:
            chart_ref: "{{ rook_ceph_cluster_project_chart }}"
            chart_version: "{{ rook_ceph_vars.kubernetes.helm.chart.version }}"
            create_namespace: true
            kubeconfig: "{{ k3s_vars.directory.config }}/k3s.yaml"
            name: "{{ rook_ceph_vars.kubernetes.helm.chart.cluster.name }}"
            namespace: "{{ rook_ceph_vars.kubernetes.namespace }}"
            update_repo_cache: true
            values: "{{ lookup('ansible.builtin.template', 'cluster_values.j2') | from_yaml }}"
            wait: true
